### ISSUE TITLE
fixunit is not work

### ISSUE THREAD

**Issue by JohnPengC** [aleksaan/diskusage#27]
i set fixunit ,but it not work, this is my options:
```
analyzer:
  path: D:\test
  depth: 1
printer:
  limit: 0
  fixunit: Mb
  sort:  name_asc
  tofile: diskusage_out.txt
```
